/*
 * #included by keys.c several times to generate a empty keymap
 *
 * @(#)$eterna: empty_metakeys.inc,v 1.3 2001/08/12 15:44:22 mrg Exp $
 */

{
	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 0 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 8 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 16 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 24 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 32 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 40 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 48 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 56 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 64 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 72 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 80 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 88 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 96 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 104 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 112 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 120 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 128 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 136 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 144 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 152 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 160 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 168 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 176 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 184 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 192 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 200 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 208 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 216 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 224 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 232 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 240 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },

	{ NOTHING,		0, 0,	(u_char *) 0 },	/* 248 */
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 },
	{ NOTHING,		0, 0,	(u_char *) 0 }
};
